import numpy as np
# a=np.array([1,2,3])
# print(a)
# print(a[0])
# print(a[1:])
# a=np.array([[1,2],[3,5],[5,7]])
# print(a[2,0],a[2])
# print(a[1,:])
# b=np.array([[1,2,3],[2,1,3]])
# print(b[1][2])
# print(b[1,2])
# print(b[1,:])
# print(b[1][:])
# a=np.array([4,5,6])
# b=np.array([1,2,3])
# print(a+b)
# print(a-b)
# print(a*b)
# print(a/b)
# a=np.array([4,5,6])
# print(a>5)
# a=np.array([0,np.pi/2,np.pi*2/2])
# # print(np.sqrt(a))
# # print(np.exp(a))
# print(np.sin(a))
# print(np.sin([0, np.pi/3,np.pi/6]))
# a=np.array([[1],[2],[3]])
# b=np.array([4,5,6,])
# print(a+b)
a=np.array([[1,2],[3,4],[5,6]])
print(a.reshape(3,2))
print(a.flatten())